# Generated by Django 4.0.10 on 2025-06-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
