# Generated by Django 4.0.10 on 2025-06-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_authors_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='banner',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
